### ISSUE TITLE
How is the current (optimized) pose concatenated with pose's from beginning?

### ISSUE THREAD

**Issue by Mechazo11** [AlejandroSilvestri/ORB_SLAM2#4]
Hello @AlejandroSilvestri,

Thank you very much for creating this repo where you documented ORB-SLAM2. It's been a great source of material for my project.

According to the classical tutorials of Visual SLAM for 2D-2D correspondence and 3D-3D correspondence, we had to concatenate current pose (T_k) with pose matrix from previous frame (C_j) using the formula Ci  = C_j dot T_k where j = i - 1. Reference https://www.researchgate.net/publication/220556161_Visual_Odometry_Tutorial (pg 9)

I was wondering where exactly this operation is done in ORB-SLAM2? My understanding is when we perform Local Map optimization, this process is "implicitly" performed but just want to be sure.

With best,
@Mechazo11

**Comment by AlejandroSilvestri** [comment]
@Mechazo11 

2D to 2D is performed by **homography** and epipolar geometry (**fundamental** matrix), only during initialization to produce the "initial map" - check out [initializer.h](https://github.com/AlejandroSilvestri/ORB_SLAM2-documented/blob/master/include/Initializer.h).  Boths methods are computed in parallel, the best approved proposal make the initial map.

After initialization, during localization, a **PnP** method is used (3D to 2D) to get the current frame pose - check out [PnPsolver.h](https://github.com/AlejandroSilvestri/ORB_SLAM2-documented/blob/master/include/PnPsolver.h).

The usual pose matrix is **Tcw**, which converts world coordinates to camera (or frame) coordinates.

**Comment by Mechazo11** [comment]
@AlejandroSilvestri isn't `Tcr` the one which converts world coordinate to camera coordinate to save intercamera relative poses? And shouldn't `Tcw` mean pose w.r.t world coordinate (global origin)?

From Tracking.cc

```
if(!mCurrentFrame.mTcw.empty())
    {
        cv::Mat Tcr = mCurrentFrame.mTcw*mCurrentFrame.mpReferenceKF->GetPoseInverse();
        // update_tracking_history()
        mlRelativeFramePoses.push_back(Tcr);
```

**Comment by AlejandroSilvestri** [comment]
@Mechazo11 

`Tab` transform from b to a, like:
`Pa = Tab Pb`

Let say **r** means wrt reference keyframe.  So

    Trw = mpReferenceKF->GetPose()
    Twr = mpReferenceKF->GetPoseInverse()
    Tcr = Tcw * Twr

The last one transforms from reference r to reference c (the current frame).  Tcr is called relative reference frame pose.

**Comment by Mechazo11** [comment]
@AlejandroSilvestri Thank you very much for your prompt reply. I think I am clear regarding how pose concatenation is happening in the ORB-SLAM pipeline.

With best,
Azmyin
